import React from 'react';

const TagItems = [
    { text: "apps", marked: false },
    { text: "blog", marked: true },
    { text: "blogcroll", marked: false },
    { text: "christmas", marked: false },
    { text: "cms", marked: false },
    { text: "coda", marked: false },
    { text: "concert", marked: false },
    { text: "daily", marked: true },
    { text: "design", marked: true },
    { text: "develop", marked: false },
    { text: "dialog", marked: false },
    { text: "drinks", marked: false },
    { text: "envato", marked: false },
    { text: "food", marked: false },
    { text: "fun", marked: false },
    { text: "gallery", marked: false },
    { text: "gift", marked: false },
    { text: "holiday", marked: false },
    { text: "icon", marked: false },
    { text: "illustration", marked: true },
    { text: "ipad", marked: false },
    { text: "iphone", marked: false },
    { text: "journal", marked: false },
    { text: "jquery", marked: true },
    { text: "label", marked: false },
    { text: "marketing", marked: false },
    { text: "mobile", marked: false },
    { text: "motion", marked: false },
    { text: "music", marked: false },
    { text: "photo", marked: false },
    { text: "profession", marked: true },
    { text: "quotation", marked: false },
    { text: "recipes", marked: false },
    { text: "show", marked: false },
    { text: "sound", marked: false },
    { text: "strategy", marked: false },
    { text: "tv", marked: false },
    { text: "typography", marked: false },
    { text: "video", marked: true }
]

export default TagItems;